In [49]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\anuma\appdata\local\programs\python\python313\lib\site-packages (2.0.44)
Requirement already satisfied: psycopg2-binary in c:\users\anuma\appdata\local\programs\python\python313\lib\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in c:\users\anuma\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\anuma\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.16.0)

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
import sqlalchemy
import numpy as np

In [2]:
from sqlalchemy import create_engine

engine_movies = create_engine(
    "postgresql+psycopg2://postgres:4232@localhost:5432/Movies"
)

print("Connected to Movies database!")

Connected to Movies database!

In [4]:
df = pd.read_sql_table("movies", engine_movies)

In [5]:
df

,movie_id,movie_name,movie_length,movie_lang,age_certificate,release_date,director_id
0,1,A Clockwork Orange,112,English,18,1972-02-02,13
1,2,Apocalypse Now,168,English,15,1979-08-15,9
2,3,Battle Royale,111,Japanese,18,2001-01-04,10
3,4,Blade Runner,121,English,15,1982-06-25,27
4,5,Chungking Express,113,Chinese,15,1996-08-03,35
5,6,City of God,145,Portuguese,18,2003-01-17,20
6,7,City of Men,140,Portuguese,15,2008-02-29,22
7,8,Cold Fish,108,Japanese,18,2010-09-12,30
8,9,Crouching Tiger Hidden Dragon,139,Chinese,12,2000-07-06,15
9,10,Eyes Wide Shut,130,English,18,1999-07-16,13
10,11,Forrest Gump,119,English,PG,1994-07-06,36
11,13,Gone with the Wind,123,English,PG,1939-12-15,8
12,14,Goodfellas,148,English,15,1990-09-19,26
13,15,Grand Budapest Hotel,117,English,PG,2014-07-03,3
14,16,House of Flying Daggers,134,Chinese,12,2004-03-12,37
15,17,In the Mood for Love,124,Chinese,12,2001-02-02,35
16,18,Jaws,134,English,12,1975-06-20,31
17,19,Leon,123,English,15,1994-11-18,5
18,20,Let the Right One In,128,Swedish,15,2008-10-24,1
19,21,Life of Brian,126,English,15,1979-08-17,12
20,22,Life of Pi,129,English,PG,2012-11-21,15
21,23,Mary Poppins,87,English,U,1964-08-29,32
22,24,Never Let Me Go,117,English,15,2010-09-15,25
23,25,Oldboy,130,Korean,18,2005-03-25,23
24,26,Pans Labyrinth,98,Spanish,PG,2006-12-29,7
25,27,Ponyo,107,Japanese,U,2009-08-14,21
26,28,Pulp Fiction,136,English,15,1994-10-14,33
27,29,Raging Bull,132,English,18,1980-11-14,26
28,30,Rushmore,104,English,12,1998-11-12,3
29,31,Spider-Man,118,English,PG,2002-05-03,24
30,32,Spider-Man 2,115,English,PG,2004-06-30,24
31,33,Spider-Man 3,112,English,PG,2007-05-04,24
32,34,Spirited Away,120,Japanese,U,2001-06-19,21
33,35,Star Wars: A New Hope,123,English,PG,1977-05-25,17
34,36,Star Wars: Empire Strikes Back,150,English,PG,1980-05-21,17
35,37,Star Wars: Return of the Jedi,139,English,PG,1983-05-25,17
36,38,Submarine,115,English,15,2011-06-03,4
37,39,Taxi Driver,117,English,15,1976-02-07,26
38,40,The Darjeeling Limited,119,English,PG,2007-09-29,3
39,41,The Fifth Element,149,English,12,1997-05-09,5
40,42,The Lives of Others,165,German,15,2007-02-09,11
41,43,The Shining,126,English,18,1980-05-23,13
42,44,The Sound of Music,91,English,U,1965-03-02,34
43,45,The Wizard of Oz,120,English,U,1939-08-25,8
44,46,There Will Be Blood,168,English,15,2007-12-26,2
45,47,"Three Billboards Outside Ebbing, Missouri",134,English,15,2017-11-10,18
46,48,Titanic,143,English,12,1997-12-19,6
47,49,Top Gun,121,English,12,1986-05-16,28
48,50,Toy Story,95,English,U,1995-11-22,14
49,51,V for Vendetta,140,English,12,2006-03-17,19
50,52,Watchmen,138,English,12,2009-03-06,29
51,53,Way of the Dragon,99,Chinese,12,1972-06-01,16

In [55]:
query ='''select * from movies as m
left join directors as d
on d.director_id = m.director_id
'''
join_tbl=pd.read_sql_query(query,engine_movies)

In [56]:
df=pd.read_csv(r"C:\Users\anuma\Downloads\archive\Weather Data.csv")

In [57]:
df.to_sql("weather", engine_movies, if_exists="replace", index=False)

22

In [58]:
join_tbl.head()

,movie_id,movie_name,movie_length,movie_lang,age_certificate,release_date,director_id,director_id,first_name,last_name,date_of_birth,add_date,update_date,nationality
0,1,A Clockwork Orange,112,English,18,1972-02-02,13,13,Stanley,Kubrick,1928-07-26,None,None,American
1,2,Apocalypse Now,168,English,15,1979-08-15,9,9,Francis,Ford Coppola,1939-04-07,None,None,American
2,3,Battle Royale,111,Japanese,18,2001-01-04,10,10,Kinji,Fukasaku,1930-07-03,None,None,Japanese
3,4,Blade Runner,121,English,15,1982-06-25,27,27,Ridley,Scott,1937-11-30,None,None,British
4,5,Chungking Express,113,Chinese,15,1996-08-03,35,35,Kar Wai,Wong,1958-07-17,None,None,Chinese

In [59]:
join_tbl[join_tbl['movie_length']>120]

,movie_id,movie_name,movie_length,movie_lang,age_certificate,release_date,director_id,director_id,first_name,last_name,date_of_birth,add_date,update_date,nationality
1,2,Apocalypse Now,168,English,15,1979-08-15,9,9,Francis,Ford Coppola,1939-04-07,None,None,American
3,4,Blade Runner,121,English,15,1982-06-25,27,27,Ridley,Scott,1937-11-30,None,None,British
5,6,City of God,145,Portuguese,18,2003-01-17,20,20,Fernando,Meirelles,1955-11-09,None,None,Brazilian
6,7,City of Men,140,Portuguese,15,2008-02-29,22,22,Paulo,Morelli,1966-03-10,None,None,Brazilian
8,9,Crouching Tiger Hidden Dragon,139,Chinese,12,2000-07-06,15,15,Ang,Lee,1954-10-23,None,None,Chinese
9,10,Eyes Wide Shut,130,English,18,1999-07-16,13,13,Stanley,Kubrick,1928-07-26,None,None,American
11,12,Gladiator,165,English,15,2000-05-05,27,27,Ridley,Scott,1937-11-30,None,None,British
12,13,Gone with the Wind,123,English,PG,1939-12-15,8,8,Victor,Fleming,1889-02-23,None,None,American
13,14,Goodfellas,148,English,15,1990-09-19,26,26,Martin,Scorsese,1942-11-17,None,None,American
15,16,House of Flying Daggers,134,Chinese,12,2004-03-12,37,37,Yimou,Zhang,1950-04-02,None,None,Chinese
16,17,In the Mood for Love,124,Chinese,12,2001-02-02,35,35,Kar Wai,Wong,1958-07-17,None,None,Chinese
17,18,Jaws,134,English,12,1975-06-20,31,31,Steven,Spielberg,1946-12-18,None,None,American
18,19,Leon,123,English,15,1994-11-18,5,5,Luc,Besson,1959-03-18,None,None,French
19,20,Let the Right One In,128,Swedish,15,2008-10-24,1,1,Tomas,Alfredson,1965-04-01,None,None,Swedish
20,21,Life of Brian,126,English,15,1979-08-17,12,12,Terry,Jones,1942-02-01,None,None,British
21,22,Life of Pi,129,English,PG,2012-11-21,15,15,Ang,Lee,1954-10-23,None,None,Chinese
24,25,Oldboy,130,Korean,18,2005-03-25,23,23,Chan-wook,Park,1963-08-23,None,None,South Korean
27,28,Pulp Fiction,136,English,15,1994-10-14,33,33,Quentin,Tarantino,1963-03-27,None,None,American
28,29,Raging Bull,132,English,18,1980-11-14,26,26,Martin,Scorsese,1942-11-17,None,None,American
34,35,Star Wars: A New Hope,123,English,PG,1977-05-25,17,17,George,Lucas,1944-05-14,None,None,American
35,36,Star Wars: Empire Strikes Back,150,English,PG,1980-05-21,17,17,George,Lucas,1944-05-14,None,None,American
36,37,Star Wars: Return of the Jedi,139,English,PG,1983-05-25,17,17,George,Lucas,1944-05-14,None,None,American
40,41,The Fifth Element,149,English,12,1997-05-09,5,5,Luc,Besson,1959-03-18,None,None,French
41,42,The Lives of Others,165,German,15,2007-02-09,11,11,Florian,Henckel von Donnersmarck,1973-05-02,None,None,German
42,43,The Shining,126,English,18,1980-05-23,13,13,Stanley,Kubrick,1928-07-26,None,None,American
45,46,There Will Be Blood,168,English,15,2007-12-26,2,2,Paul,Anderson,1970-06-26,None,None,American
46,47,"Three Billboards Outside Ebbing, Missouri",134,English,15,2017-11-10,18,18,Martin,McDonagh,1970-03-26,None,None,British
47,48,Titanic,143,English,12,1997-12-19,6,6,James,Cameron,1954-08-16,None,None,American
48,49,Top Gun,121,English,12,1986-05-16,28,28,Tony,Scott,1944-06-21,None,None,British
50,51,V for Vendetta,140,English,12,2006-03-17,19,19,James,McTeigue,1967-12-29,None,None,Australian
51,52,Watchmen,138,English,12,2009-03-06,29,29,Zack,Snyder,1966-03-01,None,None,American

In [ ]:
join_tbl["movie_length"]=join_tbl["movie_length"]

In [75]:
# join_tbl.groupby("first_name")["movie_length"].mean().head()